project:
  type: website
  output-dir: docs

website:
  title: "Forschung mit Tieren in der Schweiz"
  page-footer:
    center: |
      © 2026 Forschung mit Tieren in der Schweiz · Website developed by Simona Doneva ·
      [GitHub Repository](https://github.com/simonada/animal-research-video-series-ch) ·
      Illustrations: Sarah Steinbacher, UZH Multimedia & E-Learning Services 
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Videos"
        href: topics/index.qmd
      - text: "Über uns"
        href: about.qmd
      - text: "Über das Projekt"
        href: about-project.qmd
      - text: "Outreach"
        href: outreach.qmd
    #right:
     # - text: "DE"
      #  href: index.qmd
      #- text: "EN"
       # href: en/index.qmd

format:
  html:
    css: styles.css